name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          \& "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1"
          .\build.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          path: build/dist/

      - name: Deploy tarball
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dist
          TARGET_FOLDER: releases/nightly
