name: CI
on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build
        run: |
          pushd
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1"
          popd
          .\build.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output_windows
          path: build/dist/auth_by_steam_group.zip

  build-linux:
    runs-on: ubuntu-22.04 # Locks to a glibc version available in Debian bookwork

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install clang g++-multilib python3 python3-pip libboost-all-dev

      - name: Enable i386 packages
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -o APT::Immediate-Configure=false libboost-all-dev:i386

      - name: Build
        run:
          PATH=/home/runner/.local/bin:$PATH ./build.sh

      - name: Collect Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output_linux
          path: build/dist
