name: CI
on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          pushd
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1"
          popd
          .\build.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          name: auth_by_steam_group_windows
          path: build/dist/auth_by_steam_group.zip

  build-linux-and-deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove python2
        run: sudo apt-get remove python2 python2.7 && sudo apt-get autoremove

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install clang g++-multilib python3 python3-pip

      - name: Enable i386 packages
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -o APT::Immediate-Configure=false libcurl4-openssl-dev:i386

      - name: Build
        run:
          PATH=/home/runner/.local/bin:$PATH ./build.sh

      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: auth_by_steam_group_windows
          path: build/dist

      - name: Deploy tarball
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dist
          TARGET_FOLDER: releases/nightly
