name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Remove python2
        run: sudo apt-get remove python2 python2.7 && sudo apt-get autoremove

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install clang g++-multilib python3 python3-pip

      - name: Enable i386 packages
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libcurl4-openssl-dev:i386

      - name: Build
        run:
          PATH=/home/runner/.local/bin:$PATH ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          path: build/dist/

      - name: Deploy tarball
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dist
          TARGET_FOLDER: releases/nightly
