name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Enable i386 packages
        run: sudo dpkg --add-architecture i386 && sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install clang lib32stdc++-7-dev lib32z1-dev libc6-dev-i386 linux-libc-dev g++-multilib python libcurl4-openssl-dev:i386

      - name: Install pip
        run: wget https://bootstrap.pypa.io/2.7/get-pip.py && python2 ./get-pip.py

      - name: Build
        run: PATH=/home/runner/.local/bin:$PATH ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          path: build/dist/

      - name: Deploy tarball
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dist
          TARGET_FOLDER: releases/nightly